version: 2
jobs:
  npm-dependancies:
    docker:
      - image: node:9.3.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-dependancies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  build:
    docker:
      - image: node:9.3.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependancies
          command: npm run build
      - store_artifacts:
          path: dist/
          destination: static-project
  unit:
    docker:
      - image: node:9.3.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependancies
          command: npm run unit
      # TODO: at a later point I might store the test results here
  e2e:
    docker:
      - image: node:9.3.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependancies
          command: npm run e2e
      # TODO: at a later point I might store the test results here

workflows:
  version: 2
  build_and_test:
    jobs:
      - npm-dependancies
      - build:
          requires:
            - npm-dependancies
      - unit:
          requires:
            - build
      - e2e:
          requires:
            - build
