version: 2
jobs:
  npm-dependancies:
    docker:
      - image: node:9.3.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-dependancies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  build:
    docker:
      - image: node:9.3.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependancies
          command: npm run build
      - store_artifacts:
          path: dist/
          destination: static-project
  unit:
    docker:
      - image: node:9.3.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: run unit tests
          command: npm run unit
      # TODO: at a later point I might store the test results here
  deploy-docker-image:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker build image
          command: docker build -t thomaskleinendorst/blog-depot:latest .
      - run:
          name: push docker image to registry
          command: docker push thomaskleinendorst/blog-depot:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - npm-dependancies
      - build:
          requires:
            - npm-dependancies
      - unit:
          requires:
            - build
