version: 2
jobs:
  npm-dependancies:
    docker:
      - image: node:9.3.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-dependancies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  build:
    docker:
      - image: node:9.3.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependancies
          command: npm run build
      - store_artifacts:
          path: dist/
          destination: static-project
      - save_cache:
          key: latest-build
          paths:
            - ./dist
  unit:
    docker:
      - image: node:9.3.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: run unit tests
          command: npm run unit
      # TODO: at a later point I might store the test results here
  upload-docker-image:
    branches:
      only:
        - master
        - develop
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: latest-build
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker build image
          command: docker build -t thomaskleinendorst/blog-depot:latest -f ./docker/Dockerfile .
      - run:
          name: docker tag image
          command: docker tag thomaskleinendorst/blog-depot:latest thomaskleinendorst/blog-depot:$CIRCLE_BRANCH
      - run:
          name: push docker image to registry
          command: docker push thomaskleinendorst/blog-depot

workflows:
  version: 2
  build_and_test:
    jobs:
      - npm-dependancies
      - build:
          requires:
            - npm-dependancies
      - unit:
          requires:
            - npm-dependancies
      - upload-docker-image:
          requires:
            - unit
            - build
