version: 2
jobs:
  npm-dependancies:
    docker:
      - image: node:9.3.0
    steps:
      - checkout
      - run:
          name: update-npm-itself
          command: 'npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-dependancies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  build_and_test:
    jobs:
      - npm-dependancies
