version: "3"
services:
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
  front-end-master:
    image: thomaskleinendorst/blog-depot:master
    ports:
      - "32768:3000"
    restart: on-failure
  front-end-develop:
    image: thomaskleinendorst/blog-depot:develop
    ports:
      - "32769:3000"
    restart: on-failure

